apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-color-deployment
  labels:
    type: backend
    deployment: color
spec:
  selector:
    matchLabels:
      type: backend
      deployment: color
  replicas: 4
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        deployment: color
    spec:
      containers:
        - name: be-color-pod
          image: senagae/enadu-be:latest
          readinessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 4
          livenessProbe:
            httpGet:
              path: /test
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: DB_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: DB_USERNAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: JWT_SECRET
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: S3_ACCESS_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: S3_BUCKET
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: S3_SECRET_KEY
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: GITHUB_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: GITHUB_CLIENT_ID
            - name: FRONT_URL
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: FRONT_URL
            - name: BACK_URL
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: BACK_URL
            - name: KAFKA_URL
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: KAFKA_URL
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: EMAIL
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: EMAIL_PASSWORD
            - name: ELASTIC_HOST
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: ELASTIC_HOST
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: ELASTIC_USERNAME
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: ELASTIC_PASSWORD
      terminationGracePeriodSeconds: 0