apiVersion: v1
kind: Service
metadata:
  name: enadu-be-oauth-service
spec:
  selector:
    type: backend
    deployment: color
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800