pipeline {
    agent any

    stages {
        stage('git clone') {
            steps {
                git branch: 'be-dev', url: 'https://github.com/beyond-sw-camp/be06-fin-SENAGAE-Enadu.git'
            }
        }
        stage('Check for Changes') {
            steps {
                script {
                    def changes = sh(script: 'git diff --name-only HEAD~1 HEAD | grep -E "^back/backend/|^back/common/"', returnStatus: true)
                    if (changes != 0) {
                        echo 'No changes in batch or common, stopping pipeline.'
                        currentBuild.result = 'SUCCESS'
                        error('No changes, stopping the pipeline.')
                    } else {
                        echo 'Changes detected in backend or common, proceeding with pipeline.'
                    }
                }
            }
        }
        stage('ADD PRIVILIGES'){
            steps{
                dir('./back/backend'){
                    sh 'echo 권한 추가'
                    sh 'chmod +x gradlew'
                }
            }
        }
        stage('Test Application'){
            steps{
                dir('./back/backend'){
                    sh 'echo 단위 테스트 실행 중...'
                    sh './gradlew test'
                }
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/test-results/**/*Test.xml'
            }
        }
        stage('Build') {
            steps {
                dir('./back/backend'){
                    sh 'echo 백엔드 프로젝트 빌드 중...'
                    sh './gradlew bootJar'
                }
            }
        }
        stage('Build Docker Image'){
            steps {
                dir('./back/backend'){
                    sh 'echo 도커 이미지 빌드'
                    sh 'docker build -t senagae/enadu-be:1.$BUILD_ID .'
                }
            }
        }

        stage('Docker Push'){
            steps {
                script {
                    sh 'echo 도커 로그인'
                    sh 'docker login -u ${DOCKER_ID} -p ${DOCKER_PW}'

                    sh 'echo 도커 허브에 푸시'
                    sh 'docker push senagae/enadu-be:1.$BUILD_ID'

                    sh 'echo 푸시한 로컬 도커 이미지 삭제'
                    sh 'docker rmi senagae/enadu-be:1.$BUILD_ID'
                }
            }
        }

        stage('SSH transfer'){
            steps {
                script {
                    sshPublisher(
                        // 오류 발생 시 진행을 멈춤
                        continueOnError: false,
                        // 오류 발생 시 파이프라인을 실패시킴
                        failOnError: true,
                        // 전송자 목록
                        publishers: [
                            // SSH 전송 설명
                            sshPublisherDesc(
                                // SSH 서버 설정 이름 지정 ( master 노드 )
                                configName: "jenkins-k8s",
                                // 자세한 출력 모드 활성화
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        // 전송할 파일 지정
                                        sourceFiles: "cicd/back/backend-deployment.yaml",
                                        // 원격 디렉토리 지정 ( 원격서버로 파일을 전송할 위치 )
                                        remoteDirectory: "/home/test",
                                        // 전송 후 yaml 파일의 latest 파이프라인 빌드 숫자로 변경
                                        // backend-deployment 야멜 파일 실행
                                        execCommand: '''
                                            sed -i "s/latest/1.$BUILD_ID/g" cicd/back/backend-deployment.yaml
                                        '''
                                    ),
                                    sshTransfer(
                                        sourceFiles: "cicd/back/backend-service.yaml",
                                        remoteDirectory: "/home/test"
                                    ),
                                    sshTransfer(
                                        sourceFiles: "cicd/back/backend-oauth-service.yaml",
                                        remoteDirectory: "/home/test"
                                    ),
                                    sshTransfer(
                                        sourceFiles: "cicd/back/backend.sh",
                                        remoteDirectory: "/home/test",
                                        execCommand: '''
                                            bash cicd/back/backend.sh
                                        '''

                                    )
                                ]
                            )
                        ]
                    )
                }
            }
        }
    }
    post {
        success {
            withCredentials([string(credentialsId: 'Discord', variable: 'DISCORD')]) {
                        discordSend description: """
                        제목 : ${currentBuild.displayName}
                        결과 : ${currentBuild.result}
                        실행 시간 : ${currentBuild.duration / 1000}s
                        """,
                        link: env.BUILD_URL, result: currentBuild.currentResult,
                        title: "${env.JOB_NAME} : ${currentBuild.displayName} 성공",
                        webhookURL: "$DISCORD"
            }
        }
        failure {
            withCredentials([string(credentialsId: 'Discord', variable: 'DISCORD')]) {
                        discordSend description: """
                        제목 : ${currentBuild.displayName}
                        결과 : ${currentBuild.result}
                        실행 시간 : ${currentBuild.duration / 1000}s
                        """,
                        link: env.BUILD_URL, result: currentBuild.currentResult,
                        title: "${env.JOB_NAME} : ${currentBuild.displayName} 실패",
                        webhookURL: "$DISCORD"
            }
        }
    }
}

