apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailyrank-batch-job
  namespace: batch-dailyrank
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dailyrank-batch
              image: senagae/enadu-batch:2.2
              env:
                - name: BATCH_JOB_NAME
                  value: dailyRankingCalculateJob
                - name: BATCH_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: BATCH_DB_HOST
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_HOST
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_PASSWORD
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_USERNAME
                - name: GCLOUD_ID
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: GCLOUD_ID
          restartPolicy: OnFailure