apiVersion: batch/v1
kind: CronJob
metadata:
  name: unanswered-batch-job
  namespace: batch-unanswered
spec:
  schedule: "0 15 * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: unanswered-batch
              image: senagae/enadu-batch:latest
              env:
                - name: BATCH_JOB_NAME
                  value: unansweredJob
                - name: BATCH_DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: BATCH_DB_HOST
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_HOST
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_PASSWORD
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: DB_USERNAME
                - name: GCLOUD_ID
                  valueFrom:
                    secretKeyRef:
                      name: batch-env-secrets
                      key: GCLOUD_ID
          restartPolicy: OnFailure
      backoffLimit: 5