apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-galera-pv-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db-storage/data1"
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-galera-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db-storage/data2"
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-galera-pv-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db-storage/data3"