spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  batch:
    job:
      enabled: false
      name: ${BATCH_JOB_NAME}
    jdbc:
      initialize-schema: always
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCLOUD_ID}
          location: asia-northeast3
  datasource:
    main:
      url: ${DB_HOST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver

    batch:
      url: ${BATCH_DB_HOST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      org:
        springframework:
          batch: DEBUG
          transaction: DEBUG

ai:
  api:
    endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
    key: ${GEMINI_KEY}