server:
  port: 9090
spring:
  batch:
    job:
      name: answerJob
    jdbc:
      datasource: batchDataSource
      initialize-schema: always
  datasource:
    main:
      url: ${DB_HOST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
    batch:
      url: ${BATCH_DB_HOST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace