services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/var/lib/mysql
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.6
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS:  EXTERNAL://localhost:9092, INTERNAL://kafka:29092
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "9000:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  kibana:
    image: kibana:7.17.24
    ports:
      - "5601:5601"
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.17.24
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=qwer1234
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - xpack.security.enabled=true
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/config/index-settings.json:/usr/share/elasticsearch/config/index-settings.json
    command: >
      bash -c "
      bin/elasticsearch-plugin install analysis-nori;
      (sleep 60
      && curl -X PUT -u elastic:qwer1234 'http://localhost:9200/qna_board' -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/config/index-settings.json
      && curl -X PUT -u elastic:qwer1234 'http://localhost:9200/wiki' -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/config/index-settings.json
      && curl -X PUT -u elastic:qwer1234 'http://localhost:9200/error_archive' -H 'Content-Type: application/json' -d @/usr/share/elasticsearch/config/index-settings.json
      ) &
      /usr/local/bin/docker-entrypoint.sh;
      "
  logstash:
    image: logstash:7.17.24
    container_name: logstash
    ports:
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/mariadb-java-client-3.4.1.jar:/usr/share/logstash/mariadb-java-client-3.4.1.jar
    depends_on:
      - elasticsearch