apiVersion: v1
kind: Service
metadata:
  name: enadu-fe-service
spec:
  selector:
    type: frontend
    deployment: color
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer