apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-color-deployment
  labels:
    type: frontend
    deployment: color
spec:
  selector:
    matchLabels:
      type: frontend
      deployment: color
  replicas: 4
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
        deployment: color
    spec:
      containers:
        - name: fe-color-pod
          image: senagae/enadu-fe:latest
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 4
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
      terminationGracePeriodSeconds: 0