apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv0 # pv1, pv2 도 추가
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticsearch-storage-class
  hostPath:
    path: /mnt/data/elasticsearch