apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.17.24 # Logstash 공식 이미지 사용
          env:
            - name: ELASTICSEARCH_HOST
              value: "http://quickstart-es-http:9200"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: logstash-yml
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: mariadb-jdbc
              mountPath: /usr/share/logstash/mariadb-java-client-3.4.1.jar
              subPath: mariadb-java-client-3.4.1.jar
          ports:
            - containerPort: 5044
            - containerPort: 9600
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-configmap
        - name: logstash-yml
          configMap:
            name: logstash-yml
        - name: mariadb-jdbc
          configMap:
            name: mariadb-jdbc-driver
      terminationGracePeriodSeconds: 0